export const images = [
  { id: 1, src: "../assets/breakfast/breakfast-1.jpg" },
  { id: 2, src: "./breakfast-2.jpg" },
  { id: 3, src: "./breakfast-3.jpg" },
  { id: 4, src: "./breakfast-4.jpg" },
  { id: 5, src: "./breakfast-5.jpg" },
  { id: 6, src: "./breakfast-6.jpg" },
  { id: 7, src: "./breakfast-7.jpg" },
  { id: 8, src: "./breakfast-8.jpg" },
  { id: 9, src: "./breakfast-9.jpg" },
  { id: 10, src: "./breakfast-10.jpg" },
  { id: 11, src: "./breakfast-11.jpg" },
  { id: 12, src: "./breakfast-12.jpg" },
  { id: 13, src: "./breakfast-13.jpg" },
  { id: 14, src: "./breakfast-14.jpg" },
  { id: 15, src: "./breakfast-15.jpg" },
  { id: 16, src: "./breakfast-16.jpg" },
  { id: 17, src: "./breakfast-17.jpg" },
  { id: 18, src: "./breakfast-18.jpg" },
  { id: 19, src: "./breakfast-19.jpg" },
  { id: 20, src: "./breakfast-20.jpg" },
  { id: 21, src: "./breakfast-21.jpg" },
  { id: 22, src: "./breakfast-22.jpg" },
  { id: 23, src: "./breakfast-23.jpg" },
  { id: 24, src: "./breakfast-24.jpg" },
  { id: 25, src: "./breakfast-25.jpg" },
  { id: 26, src: "./breakfast-26.jpg" },
  { id: 27, src: "./breakfast-27.jpg" },
  { id: 28, src: "./breakfast-28.jpg" },
];

export default images;
